version: "3.8"

services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
      args:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - mynetwork

  auth:
    container_name: auth
    build:
      context: ./oauth2
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/code
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - mynetwork

volumes:
  pgdata:
    driver: local

networks:
  mynetwork:
    driver: bridge
